# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e41cb8c6d92766253659bf186d0d337142a0414e1c9772fc2972c212e414e8c1b8ed7b7149a098104b6150352f62cc50fce6bed63342723e3ab3fa9757af86

test:
  secret_key_base: 6747bb6e75ade4716c1e6a3d91bb38c7a88f29898f476769f430553c545fb6aa6cbf0130b40001a2ca11abec581c594711141032015d4f7e2b978d072a3a0836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
